### ISSUE TITLE
Unit 4 Error on Android Pixel-3a

### ISSUE THREAD

**Issue by eddylai** [MicrosoftDocs/mslearn-dotnetmaui-store-local-data#10]
works for "Windows Machine", but got error on click "Add Person":

System.IO.FileNotFoundException
  Message=Could not load file or assembly 'SQLitePCLRaw.provider.dynamic_cdecl, Version=2.0.4.976, Culture=neutral, PublicKeyToken=b68184102cba0b3b' or one of its dependencies.

Im using: Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.3.0 Preview 2.0
![Screenshot 2022-06-20 131735](https://user-images.githubusercontent.com/961578/174530133-920c8d63-9c80-4eca-8a18-a39339d9bd65.jpg)

**Comment by OculiViridi** [comment]
Got the same error when executing on Android emulator `Pixel 5 - API 31 (Android 12.0)`.

**Comment by benmayo10** [comment]
I had the same issue- make sure you follow the steps in the tutorial. You need to do this:

> 4. Also install the SQLitePCLRaw.provider.dynamic_cdecl by searching for it in NuGet and clicking install.

**Comment by nnn149** [comment]
> 我遇到了同样的问题 - 确保按照教程中的步骤操作。您需要执行以下操作：
> 
> > 4. 此外，通过在 NuGet 中搜索SQLitePCLRaw.provider.dynamic_cdecl并单击“安装”来安装它。

You saved me

**Comment by itldg** [comment]
> I had the same issue- make sure you follow the steps in the tutorial. You need to do this:
> 
> > 4. Also install the SQLitePCLRaw.provider.dynamic_cdecl by searching for it in NuGet and clicking install.

很有帮助

**Comment by jamesmontemagno** [comment]
Please install: SQLitePCLRaw.bundle_green
