### ISSUE TITLE
Use of Async Prevents Build From Working

### ISSUE THREAD

**Issue by farmergreg** [MicrosoftDocs/mslearn-dotnetmaui-store-local-data#3]
Unit 4 suggests running the application after setting up the sql lite connection. This won't work because some of the code is async.

I would suggest making 3 branches; each in various stages of completion.
- main branch; code with all of the todo's
- sync branch; complete code demonstrating sync use of sqlite
- async branch; complete code demonstrating async use of sqlite.

**Comment by Thebe01** [comment]
Module MainPage.xaml.cs
Removing async in method public async void OnNewButtonClicked(object sender, EventArgs args)
and await in await App.PersonRepo.AddNewPerson(newPerson.Text);
and removing async in method public async void OnGetButtonClicked(object sender, EventArgs args)
and await in List<Person> people = await App.PersonRepo.GetAllPeople();
will allow app to build and run without error.

**Comment by rschuerer** [comment]
Removing the await's is enough no need to remove the async attribute of the methods
