### ISSUE TITLE
iOS won't run without SQLitePCLRaw.bundle_green

### ISSUE THREAD

**Issue by BaldeGH** [MicrosoftDocs/mslearn-dotnetmaui-store-local-data#7]
Tried running this example on iOS simulator, but it won't initial the db without the nuget package SQLitePCLRaw.bundle_green. It's not mentioned in the tutorial.

**Comment by jamesmontemagno** [comment]
I am fixing this up in the next update for .NET 8 in the module. Thanks for the feedback.
